DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  displayName TEXT NOT NULL,
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  images TEXT NOT NULL,
  /*author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,*/
  texts TEXT NOT NULL,
  username TEXT NOT NULL,
  verified BIT
  /*FOREIGN KEY (author_id) REFERENCES user (id)*/
);